# Import libraries required for data loading and analysis

In [1]:

import kagglehub
import os
import pandas as pd

path = kagglehub.dataset_download("nikitatkachenko/19332-spotify-songs")


print(os.listdir(path))

df = pd.read_csv(
    os.path.join(path, "19332_Spotify_Songs.csv"),
    encoding="latin1"
)

['19332_Spotify_Songs.csv']

C:\Users\Tejus\AppData\Local\Temp\ipykernel_2420\2651407780.py:13: DtypeWarning: Columns (9,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

# Import libraries for plotting

In [2]:

import matplotlib.pyplot as plt
import seaborn as sns

# Display the first five rows of the dataset

In [3]:
df.head()

,id,artists,available_markets,disc_number,duration_ms.x,explicit,href,is_local,name,popularity,...,instrumentalness,liveness,valence,tempo,type.y,uri.y,track_href,analysis_url,duration_ms.y,time_signature
0,000xQL6tZNLJzIrtIgxqSl,https://api.spotify.com/v1/artists/5ZsFI1h6hId...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,188490,FALSE,https://api.spotify.com/v1/tracks/000xQL6tZNLJ...,FALSE,Still Got Time (feat. PARTYNEXTDOOR),63,...,0.000000,0.0852,0.524,120.963,audio_features,spotify:track:000xQL6tZNLJzIrtIgxqSl,https://api.spotify.com/v1/tracks/000xQL6tZNLJ...,https://api.spotify.com/v1/audio-analysis/000x...,188491.0,4.0
1,001UkMQHw4zXfFNdKpwXAF,https://api.spotify.com/v1/artists/0XKOBt59crn...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,191053,FALSE,https://api.spotify.com/v1/tracks/001UkMQHw4zX...,FALSE,Brand New Man - with Luke Combs,68,...,0.000079,0.2900,0.562,127.061,audio_features,spotify:track:001UkMQHw4zXfFNdKpwXAF,https://api.spotify.com/v1/tracks/001UkMQHw4zX...,https://api.spotify.com/v1/audio-analysis/001U...,191053.0,4.0
2,003FTlCpBTM4eSqYSWPv4H,https://api.spotify.com/v1/artists/3vAaWhdBR38...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,233266,FALSE,https://api.spotify.com/v1/tracks/003FTlCpBTM4...,FALSE,"Swing, Swing",67,...,0.128000,0.0385,0.318,127.947,audio_features,spotify:track:003FTlCpBTM4eSqYSWPv4H,https://api.spotify.com/v1/tracks/003FTlCpBTM4...,https://api.spotify.com/v1/audio-analysis/003F...,233267.0,4.0
3,003vvx7Niy0yvhvHt4a68B,https://api.spotify.com/v1/artists/0C0XlULifJt...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,222973,FALSE,https://api.spotify.com/v1/tracks/003vvx7Niy0y...,FALSE,Mr. Brightside,80,...,0.000000,0.0995,0.236,148.033,audio_features,spotify:track:003vvx7Niy0yvhvHt4a68B,https://api.spotify.com/v1/tracks/003vvx7Niy0y...,https://api.spotify.com/v1/audio-analysis/003v...,222973.0,4.0
4,005lwxGU1tms6HGELIcUv9,https://api.spotify.com/v1/artists/6jJ0s89eD6G...,"CA, JP, US",1,179640,FALSE,https://api.spotify.com/v1/tracks/005lwxGU1tms...,FALSE,I Kissed A Girl,68,...,0.000000,0.1320,0.696,129.996,audio_features,spotify:track:005lwxGU1tms6HGELIcUv9,https://api.spotify.com/v1/tracks/005lwxGU1tms...,https://api.spotify.com/v1/audio-analysis/005l...,179640.0,4.0

# Check the number of rows and columns in the dataset

In [4]:
df.shape

(19335, 46)

# Display the names of all columns

In [5]:
df.columns

Index(['id', 'artists', 'available_markets', 'disc_number', 'duration_ms.x',
       'explicit', 'href', 'is_local', 'name', 'popularity', 'preview_url',
       'track_number', 'type.x', 'uri.x', 'album.album_type', 'album.artists',
       'album.available_markets', 'album.href', 'album.id', 'album.images',
       'album.name', 'album.release_date', 'album.release_date_precision',
       'album.total_tracks', 'album.type', 'album.uri',
       'album.external_urls.spotify', 'external_ids.isrc',
       'external_urls.spotify', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'type.y', 'uri.y', 'track_href', 'analysis_url',
       'duration_ms.y', 'time_signature'],
      dtype='object')

# Check the structure, data types, and non-null values

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19335 entries, 0 to 19334
Data columns (total 46 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            19333 non-null  object
 1   artists                       19335 non-null  object
 2   available_markets             19335 non-null  object
 3   disc_number                   19335 non-null  int64
 4   duration_ms.x                 19335 non-null  object
 5   explicit                      19335 non-null  object
 6   href                          19335 non-null  object
 7   is_local                      19335 non-null  object
 8   name                          19333 non-null  object
 9   popularity                    19334 non-null  object
 10  preview_url                   11811 non-null  object
 11  track_number                  19334 non-null  object
 12  type.x                        19334 non-null  object
 13  uri.x                         19333 non-null  object
 14  album.album_type              19333 non-null  object
 15  album.artists                 19333 non-null  object
 16  album.available_markets       19333 non-null  object
 17  album.href                    19333 non-null  object
 18  album.id                      19333 non-null  object
 19  album.images                  19333 non-null  object
 20  album.name                    19333 non-null  object
 21  album.release_date            19331 non-null  object
 22  album.release_date_precision  19331 non-null  object
 23  album.total_tracks            19331 non-null  object
 24  album.type                    19331 non-null  object
 25  album.uri                     19331 non-null  object
 26  album.external_urls.spotify   19328 non-null  object
 27  external_ids.isrc             19328 non-null  object
 28  external_urls.spotify         19328 non-null  object
 29  danceability                  19328 non-null  float64
 30  energy                        19328 non-null  float64
 31  key                           19328 non-null  float64
 32  loudness                      19328 non-null  float64
 33  mode                          19328 non-null  float64
 34  speechiness                   19328 non-null  float64
 35  acousticness                  19328 non-null  float64
 36  instrumentalness              19328 non-null  float64
 37  liveness                      19328 non-null  float64
 38  valence                       19328 non-null  float64
 39  tempo                         19328 non-null  float64
 40  type.y                        19328 non-null  object
 41  uri.y                         19328 non-null  object
 42  track_href                    19328 non-null  object
 43  analysis_url                  19328 non-null  object
 44  duration_ms.y                 19328 non-null  float64
 45  time_signature                19328 non-null  float64
dtypes: float64(13), int64(1), object(32)
memory usage: 6.8+ MB

# Check the number of missing values in each column

In [7]:
df.isnull().sum()

id                                 2
artists                            0
available_markets                  0
disc_number                        0
duration_ms.x                      0
explicit                           0
href                               0
is_local                           0
name                               2
popularity                         1
preview_url                     7524
track_number                       1
type.x                             1
uri.x                              2
album.album_type                   2
album.artists                      2
album.available_markets            2
album.href                         2
album.id                           2
album.images                       2
album.name                         2
album.release_date                 4
album.release_date_precision       4
album.total_tracks                 4
album.type                         4
album.uri                          4
album.external_urls.spotify        7
external_ids.isrc                  7
external_urls.spotify              7
danceability                       7
energy                             7
key                                7
loudness                           7
mode                               7
speechiness                        7
acousticness                       7
instrumentalness                   7
liveness                           7
valence                            7
tempo                              7
type.y                             7
uri.y                              7
track_href                         7
analysis_url                       7
duration_ms.y                      7
time_signature                     7
dtype: int64

# Check the number of duplicate rows

In [8]:
df.duplicated().sum()

np.int64(0)

# Generate descriptive statistics for numerical columns

In [9]:
df.describe()

,disc_number,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms.y,time_signature
count,19335.000000,19328.000000,19328.000000,19328.000000,19328.000000,19328.000000,19328.000000,19328.000000,19328.000000,19328.000000,19328.000000,19328.000000,1.932800e+04,19328.000000
mean,1.020222,0.615997,0.584217,5.191743,-8.605355,0.645281,0.107343,0.308663,0.102164,0.182456,0.491398,119.794873,2.086390e+05,3.896368
std,0.248414,0.179863,0.236897,3.568570,5.803552,0.478440,0.111756,0.321930,0.266955,0.147103,0.242762,30.972588,6.608957e+04,0.461114
min,1.000000,0.000000,0.000020,0.000000,-54.376000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.339000e+03,0.000000
25%,1.000000,0.507000,0.443000,2.000000,-9.714000,0.000000,0.038200,0.039500,0.000000,0.096700,0.304000,94.986750,1.727650e+05,4.000000
50%,1.000000,0.638000,0.620000,5.000000,-6.816000,1.000000,0.056500,0.175000,0.000002,0.122000,0.490000,119.894500,2.048350e+05,4.000000
75%,1.000000,0.748000,0.765000,8.000000,-5.085000,1.000000,0.127000,0.517000,0.001130,0.219000,0.678000,140.068000,2.370200e+05,4.000000
max,15.000000,0.985000,1.000000,11.000000,1.060000,1.000000,0.954000,0.996000,1.000000,0.993000,1.000000,230.401000,1.167000e+06,5.000000

# Check the number of unique values in each column

In [10]:
df.nunique()

id                              19332
artists                          8788
available_markets                 786
disc_number                        10
duration_ms.x                   14072
explicit                            5
href                            19334
is_local                            5
name                            16232
popularity                        197
preview_url                     11549
track_number                      494
type.x                              5
uri.x                           19332
album.album_type                    6
album.artists                    5813
album.available_markets           759
album.href                      11035
album.id                        11035
album.images                    11035
album.name                      10585
album.release_date               3350
album.release_date_precision        6
album.total_tracks                115
album.type                          4
album.uri                       11032
album.external_urls.spotify     11031
external_ids.isrc               17455
external_urls.spotify           19328
danceability                      961
energy                           1478
key                                12
loudness                         9757
mode                                2
speechiness                      1280
acousticness                     3042
instrumentalness                 3777
liveness                         1464
valence                          1390
tempo                           14335
type.y                              1
uri.y                           19328
track_href                      19328
analysis_url                    19328
duration_ms.y                   14089
time_signature                      5
dtype: int64

## First Impression

The dataset contains information about Spotify songs and playlists, with both numerical and categorical columns. The dataset has a large number of records and provides different types of information about songs, such as genres, playlists, and audio-related features. The initial inspection helped identify the structure, data types, missing values, and duplicate records in the dataset. Overall, the dataset appears suitable for further analysis and visualization.