
### WEEK 2: KNOW YOUR DATA

#### Project Title
Spotify Music Trends and Audio Features Analysis Using Data Science and Visualization

#### Course
24ADI204 – Data Science and Visualization

#### Team
DSV Team 9

#### Aim
To load, inspect, and understand the structure and quality of the Spotify Songs dataset using Python, Pandas, and NumPy.

#### Objectives
1. Load the Spotify dataset from a CSV file.
2. Identify the number of rows and columns.
3. Examine the first and last five records.
4. Identify column names and data types.
5. Calculate preliminary descriptive statistics.
6. Identify missing values and duplicate records.
7. Generate an automated First Impression Data Quality Report.


### 1. Introduction

Data understanding is an important step in the data science workflow. Before performing data cleaning, statistical analysis, or visualization, it is necessary to examine the structure and quality of the dataset.

In this experiment, the Spotify Songs dataset is explored using Pandas and NumPy.

The analysis focuses on understanding the dataset structure, identifying data types, detecting missing values, and checking duplicate records.

The findings will help determine suitable preprocessing techniques for Week 3.


### 2. Importing Required Libraries

The following Python libraries are used:

- **Pandas:** To load, inspect, and analyze the dataset.
- **NumPy:** To perform numerical operations and calculations.

In [33]:

import pandas as pd
import numpy as np

print("Pandas Version:", pd.__version__)
print("NumPy Version:", np.__version__)
print("Libraries imported successfully!")

Pandas Version: 3.0.6
NumPy Version: 2.4.6
Libraries imported successfully!


### 3. Loading the Spotify Dataset

The Spotify Songs dataset is stored in CSV format.

The `pd.read_csv()` function is used to load the dataset into a Pandas DataFrame.

The original dataset is preserved without any modifications during Week 2.

In [34]:

from pathlib import Path

file_name = "DSV_Team-9_Raw_Dataset.csv"
file_path = Path(file_name)

# Search for the dataset in the current folder
if not file_path.exists():
    print("Dataset not found in current folder.")
    print("Current folder:", Path.cwd())

    # Enter the complete CSV path if necessary
    file_path = Path(
        input("Enter full path of your CSV file: ").strip().strip('"')
    )

if not file_path.is_file():
    raise FileNotFoundError(
        f"Dataset not found: {file_path}"
    )

df = pd.read_csv(
    file_path,
    encoding="latin1",
    low_memory=False
)

print("Dataset loaded successfully!")
print("Dataset Shape:", df.shape)

Dataset loaded successfully!
Dataset Shape: (19335, 46)


### 4. Previewing the Dataset

The `head()` function displays the first five records, while the `tail()` function displays the last five records.

These functions help us understand how the dataset is organized and what information is available.

In [35]:

df.head()

,id,artists,available_markets,disc_number,duration_ms.x,explicit,href,is_local,name,popularity,...,instrumentalness,liveness,valence,tempo,type.y,uri.y,track_href,analysis_url,duration_ms.y,time_signature
0,000xQL6tZNLJzIrtIgxqSl,https://api.spotify.com/v1/artists/5ZsFI1h6hId...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,188490,FALSE,https://api.spotify.com/v1/tracks/000xQL6tZNLJ...,FALSE,Still Got Time (feat. PARTYNEXTDOOR),63,...,0.000000,0.0852,0.524,120.963,audio_features,spotify:track:000xQL6tZNLJzIrtIgxqSl,https://api.spotify.com/v1/tracks/000xQL6tZNLJ...,https://api.spotify.com/v1/audio-analysis/000x...,188491.0,4.0
1,001UkMQHw4zXfFNdKpwXAF,https://api.spotify.com/v1/artists/0XKOBt59crn...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,191053,FALSE,https://api.spotify.com/v1/tracks/001UkMQHw4zX...,FALSE,Brand New Man - with Luke Combs,68,...,0.000079,0.2900,0.562,127.061,audio_features,spotify:track:001UkMQHw4zXfFNdKpwXAF,https://api.spotify.com/v1/tracks/001UkMQHw4zX...,https://api.spotify.com/v1/audio-analysis/001U...,191053.0,4.0
2,003FTlCpBTM4eSqYSWPv4H,https://api.spotify.com/v1/artists/3vAaWhdBR38...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,233266,FALSE,https://api.spotify.com/v1/tracks/003FTlCpBTM4...,FALSE,"Swing, Swing",67,...,0.128000,0.0385,0.318,127.947,audio_features,spotify:track:003FTlCpBTM4eSqYSWPv4H,https://api.spotify.com/v1/tracks/003FTlCpBTM4...,https://api.spotify.com/v1/audio-analysis/003F...,233267.0,4.0
3,003vvx7Niy0yvhvHt4a68B,https://api.spotify.com/v1/artists/0C0XlULifJt...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,222973,FALSE,https://api.spotify.com/v1/tracks/003vvx7Niy0y...,FALSE,Mr. Brightside,80,...,0.000000,0.0995,0.236,148.033,audio_features,spotify:track:003vvx7Niy0yvhvHt4a68B,https://api.spotify.com/v1/tracks/003vvx7Niy0y...,https://api.spotify.com/v1/audio-analysis/003v...,222973.0,4.0
4,005lwxGU1tms6HGELIcUv9,https://api.spotify.com/v1/artists/6jJ0s89eD6G...,"CA, JP, US",1,179640,FALSE,https://api.spotify.com/v1/tracks/005lwxGU1tms...,FALSE,I Kissed A Girl,68,...,0.000000,0.1320,0.696,129.996,audio_features,spotify:track:005lwxGU1tms6HGELIcUv9,https://api.spotify.com/v1/tracks/005lwxGU1tms...,https://api.spotify.com/v1/audio-analysis/005l...,179640.0,4.0

In [36]:

df.tail()

,id,artists,available_markets,disc_number,duration_ms.x,explicit,href,is_local,name,popularity,...,instrumentalness,liveness,valence,tempo,type.y,uri.y,track_href,analysis_url,duration_ms.y,time_signature
19330,7zVCrzzEJU7u24sbJPXA5W,https://api.spotify.com/v1/artists/3oSJ7TBVCWM...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,188253,FALSE,https://api.spotify.com/v1/tracks/7zVCrzzEJU7u...,FALSE,What Ifs (feat. Lauren Alaina),74,...,0.0000,0.1720,0.687,125.976,audio_features,spotify:track:7zVCrzzEJU7u24sbJPXA5W,https://api.spotify.com/v1/tracks/7zVCrzzEJU7u...,https://api.spotify.com/v1/audio-analysis/7zVC...,188253.0,4.0
19331,7zwn1eykZtZ5LODrf7c0tS,https://api.spotify.com/v1/artists/77SW9BnxLY8...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,153000,FALSE,https://api.spotify.com/v1/tracks/7zwn1eykZtZ5...,FALSE,You Get Me So High,67,...,0.0791,0.1520,0.387,88.036,audio_features,spotify:track:7zwn1eykZtZ5LODrf7c0tS,https://api.spotify.com/v1/tracks/7zwn1eykZtZ5...,https://api.spotify.com/v1/audio-analysis/7zwn...,153000.0,4.0
19332,7zxRMhXxJMQCeDDg0rKAVo,https://api.spotify.com/v1/artists/7rkW85dBwwr...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,179773,TRUE,https://api.spotify.com/v1/tracks/7zxRMhXxJMQC...,FALSE,Some Way,70,...,0.0000,0.0919,0.340,154.962,audio_features,spotify:track:7zxRMhXxJMQCeDDg0rKAVo,https://api.spotify.com/v1/tracks/7zxRMhXxJMQC...,https://api.spotify.com/v1/audio-analysis/7zxR...,179773.0,4.0
19333,7zY8YswnsfvcHk4Xshhelm,https://api.spotify.com/v1/artists/0q9lPhJHW5R...,"CA, CR, DO, GT, HN, MX, NI, PA, SV, US",1,264840,FALSE,https://api.spotify.com/v1/tracks/7zY8Yswnsfvc...,FALSE,Zen Island,40,...,0.0000,0.2420,0.472,75.990,audio_features,spotify:track:7zY8YswnsfvcHk4Xshhelm,https://api.spotify.com/v1/tracks/7zY8Yswnsfvc...,https://api.spotify.com/v1/audio-analysis/7zY8...,264840.0,4.0
19334,7zzFMgUlCC0ZUQGXkf6t1B,https://api.spotify.com/v1/artists/0AsThoR4KZS...,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",1,195426,FALSE,https://api.spotify.com/v1/tracks/7zzFMgUlCC0Z...,FALSE,Lonely,56,...,0.0906,0.1090,0.241,94.984,audio_features,spotify:track:7zzFMgUlCC0ZUQGXkf6t1B,https://api.spotify.com/v1/tracks/7zzFMgUlCC0Z...,https://api.spotify.com/v1/audio-analysis/7zzF...,195427.0,4.0


#### Observation

The dataset contains information about Spotify songs, artists, albums, popularity, and audio characteristics.

Each row represents a song record, while the 46 columns contain different attributes related to that record.

The dataset includes both categorical and numerical information.


### 5. Understanding Dataset Structure

The structure of the dataset is examined using:

- `df.shape` – Number of rows and columns.
- `df.columns` – Names of all columns.
- `df.dtypes` – Data types of each column.
- `df.info()` – Non-null counts, data types, and memory usage.

This analysis helps identify columns that may require preprocessing.

In [37]:

print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

print("\nColumn Names:")
for i, column in enumerate(df.columns, 1):
    print(f"{i}. {column}")

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()

Total Rows: 19335
Total Columns: 46

Column Names:
1. id
2. artists
3. available_markets
4. disc_number
5. duration_ms.x
6. explicit
7. href
8. is_local
9. name
10. popularity
11. preview_url
12. track_number
13. type.x
14. uri.x
15. album.album_type
16. album.artists
17. album.available_markets
18. album.href
19. album.id
20. album.images
21. album.name
22. album.release_date
23. album.release_date_precision
24. album.total_tracks
25. album.type
26. album.uri
27. album.external_urls.spotify
28. external_ids.isrc
29. external_urls.spotify
30. danceability
31. energy
32. key
33. loudness
34. mode
35. speechiness
36. acousticness
37. instrumentalness
38. liveness
39. valence
40. tempo
41. type.y
42. uri.y
43. track_href
44. analysis_url
45. duration_ms.y
46. time_signature

Data Types:
id                                  str
artists                             str
available_markets                   str
disc_number                       int64
duration_ms.x                       str
explicit                            str
href                                str
is_local                            str
name                                str
popularity                          str
preview_url                         str
track_number                        str
type.x                              str
uri.x                               str
album.album_type                    str
album.artists                       str
album.available_markets             str
album.href                          str
album.id                            str
album.images                        str
album.name                          str
album.release_date                  str
album.release_date_precision        str
album.total_tracks                  str
album.type                          str
album.uri                           str
album.external_urls.spotify         str
external_ids.isrc                   str
external_urls.spotify               str
danceability                    float64
energy                          float64
key                             float64
loudness                        float64
mode                            float64
speechiness                     float64
acousticness                    float64
instrumentalness                float64
liveness                        float64
valence                         float64
tempo                           float64
type.y                              str
uri.y                               str
track_href                          str
analysis_url                        str
duration_ms.y                   float64
time_signature                  float64
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 19335 entries, 0 to 19334
Data columns (total 46 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            19333 non-null  str
 1   artists                       19335 non-null  str
 2   available_markets             19335 non-null  str
 3   disc_number                   19335 non-null  int64
 4   duration_ms.x                 19335 non-null  str
 5   explicit                      19335 non-null  str
 6   href                          19335 non-null  str
 7   is_local                      19335 non-null  str
 8   name                          19333 non-null  str
 9   popularity                    19334 non-null  str
 10  preview_url                   11811 non-null  str
 11  track_number                  19334 non-null  str
 12  type.x                        19334 non-null  str
 13  uri.x                         19333 non-null  str
 14  album.album_type              19333 non-null  str
 15  album.artists                 19333 non-null  str
 16  album.available_markets       19333 non-null  str
 17  album.href                    19333 non-null  str
 18  album.id                      19333 non-null  str
 19  album.images                  19333 non-null  str
 20  album.name                    19333 non-null  str
 21  album.release_date            19331 non-null  str
 22  album.release_date_precision  19331 non-null  str
 23  album.total_tracks            19331 non-null  str
 24  album.type                    19331 non-null  str
 25  album.uri                     19331 non-null  str
 26  album.external_urls.spotify   19328 non-null  str
 27  external_ids.isrc             19328 non-null  str
 28  external_urls.spotify         19328 non-null  str
 29  danceability                  19328 non-null  float64
 30  energy                        19328 non-null  float64
 31  key                           19328 non-null  float64
 32  loudness                      19328 non-null  float64
 33  mode                          19328 non-null  float64
 34  speechiness                   19328 non-null  float64
 35  acousticness                  19328 non-null  float64
 36  instrumentalness              19328 non-null  float64
 37  liveness                      19328 non-null  float64
 38  valence                       19328 non-null  float64
 39  tempo                         19328 non-null  float64
 40  type.y                        19328 non-null  str
 41  uri.y                         19328 non-null  str
 42  track_href                    19328 non-null  str
 43  analysis_url                  19328 non-null  str
 44  duration_ms.y                 19328 non-null  float64
 45  time_signature                19328 non-null  float64
dtypes: float64(13), int64(1), str(32)
memory usage: 6.8 MB


#### Observation

The Spotify dataset contains 19,335 rows and 46 columns.

The columns include song identifiers, artist information, album details, popularity, and audio features.

Some columns contain numerical information stored as object data types.

These inconsistencies will be examined during Week 3.


### 6. Preliminary Descriptive Statistics

Descriptive statistics provide an initial summary of the dataset.

For numerical attributes, the `describe()` function calculates:

- Count
- Mean
- Standard deviation
- Minimum value
- Quartiles
- Maximum value

For categorical attributes, it provides information about unique values and frequently occurring entries.

In [38]:

# Numerical columns
numerical_summary = df.describe()

display(numerical_summary.T)

,count,mean,std,min,25%,50%,75%,max
disc_number,19335.0,1.020222,0.248414,1.00000,1.00000,1.000000,1.00000,15.000
danceability,19328.0,0.615997,0.179863,0.00000,0.50700,0.638000,0.74800,0.985
energy,19328.0,0.584217,0.236897,0.00002,0.44300,0.620000,0.76500,1.000
key,19328.0,5.191743,3.568570,0.00000,2.00000,5.000000,8.00000,11.000
loudness,19328.0,-8.605355,5.803552,-54.37600,-9.71400,-6.816000,-5.08500,1.060
mode,19328.0,0.645281,0.478440,0.00000,0.00000,1.000000,1.00000,1.000
speechiness,19328.0,0.107343,0.111756,0.00000,0.03820,0.056500,0.12700,0.954
acousticness,19328.0,0.308663,0.321930,0.00000,0.03950,0.175000,0.51700,0.996
instrumentalness,19328.0,0.102164,0.266955,0.00000,0.00000,0.000002,0.00113,1.000
liveness,19328.0,0.182456,0.147103,0.00000,0.09670,0.122000,0.21900,0.993
valence,19328.0,0.491398,0.242762,0.00000,0.30400,0.490000,0.67800,1.000
tempo,19328.0,119.794873,30.972588,0.00000,94.98675,119.894500,140.06800,230.401
duration_ms.y,19328.0,208639.039528,66089.565365,3339.00000,172765.00000,204835.000000,237020.00000,1167000.000
time_signature,19328.0,3.896368,0.461114,0.00000,4.00000,4.000000,4.00000,5.000

In [39]:

# Categorical columns
categorical_summary = df.describe(
    include=["object", "string", "category"]
)

display(categorical_summary.T)

,count,unique,top,freq
id,19333,19332,í,2
artists,19335,8788,https://api.spotify.com/v1/artists/06HL4z0CvFA...,148
available_markets,19335,786,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",12228
duration_ms.x,19335,14072,198720,23
explicit,19335,5,FALSE,13557
href,19335,19334,https://open.spotify.com/album/2rQlPhe76mnmviB...,2
is_local,19335,5,FALSE,19331
name,19333,16232,A Ella,23
popularity,19334,104,64,871
preview_url,11811,11549,https://p.scdn.co/mp3-preview/7e6e8a265e6c0bf7...,3
track_number,19334,375,1,5702
type.x,19334,5,track,19330
uri.x,19333,19332,0,2
album.album_type,19333,6,album,13730
album.artists,19333,5813,https://api.spotify.com/v1/artists/0LyfQWJT6nX...,1216
album.available_markets,19333,759,"AD, AE, AL, AR, AT, AU, BA, BE, BG, BH, BO, BR...",12258
album.href,19333,11035,https://api.spotify.com/v1/albums/2B2OGZYSkJaC...,171
album.id,19333,11035,2B2OGZYSkJaCjo6yjJhPVZ,171
album.images,19333,11035,"640, 300, 64, https://i.scdn.co/image/ab67616d...",171
album.name,19333,10585,Bach: A Life of Music,171
album.release_date,19331,3350,2020-12-04,974
album.release_date_precision,19331,6,day,18512
album.total_tracks,19331,115,1,3495
album.type,19331,4,album,19328
album.uri,19331,11032,spotify:album:2B2OGZYSkJaCjo6yjJhPVZ,171
album.external_urls.spotify,19328,11031,https://open.spotify.com/album/2B2OGZYSkJaCjo6...,171
external_ids.isrc,19328,17455,USUM71703010,23
external_urls.spotify,19328,19328,https://open.spotify.com/track/000xQL6tZNLJzIr...,1
type.y,19328,1,audio_features,19328
uri.y,19328,19328,spotify:track:000xQL6tZNLJzIrtIgxqSl,1
track_href,19328,19328,https://api.spotify.com/v1/tracks/000xQL6tZNLJ...,1
analysis_url,19328,19328,https://api.spotify.com/v1/audio-analysis/000x...,1


#### Observation

The numerical summary provides information about the range and distribution of Spotify audio features.

The categorical summary identifies unique values and frequently occurring entries.

Some numerical attributes may be stored as text and therefore may not appear in the numerical summary.

Detailed statistical analysis will be performed in Week 4.


### 7. Missing Value Analysis

Missing values occur when information is unavailable for certain records.

The `isnull()` function identifies missing values, while `sum()` calculates their total count.

Missing percentages are calculated to measure the completeness of each column.

During Week 2, missing values are only identified and documented. They will be handled during Week 3.

In [40]:

missing_report = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().mean() * 100
    ).round(2)
})

missing_report = missing_report.sort_values(
    by="Missing Count",
    ascending=False
)

display(missing_report)

print(
    "Total Missing Cells:",
    df.isnull().sum().sum()
)

print(
    "Rows with Missing Values:",
    df.isnull().any(axis=1).sum()
)

print(
    "Columns with Missing Values:",
    (df.isnull().sum() > 0).sum()
)

                              Missing Count  Missing Percentage
preview_url                            7524               38.91
mode                                      7                0.04
speechiness                               7                0.04
acousticness                              7                0.04
instrumentalness                          7                0.04
liveness                                  7                0.04
valence                                   7                0.04
tempo                                     7                0.04
type.y                                    7                0.04
uri.y                                     7                0.04
danceability                              7                0.04
external_urls.spotify                     7                0.04
external_ids.isrc                         7                0.04
album.external_urls.spotify               7                0.04
track_href                                7                0.04
analysis_url                              7                0.04
duration_ms.y                             7                0.04
time_signature                            7                0.04
key                                       7                0.04
loudness                                  7                0.04
energy                                    7                0.04
album.uri                                 4                0.02
album.release_date_precision              4                0.02
album.type                                4                0.02
album.total_tracks                        4                0.02
album.release_date                        4                0.02
id                                        2                0.01
album.href                                2                0.01
uri.x                                     2                0.01
name                                      2                0.01
album.images                              2                0.01
album.id                                  2                0.01
album.available_markets                   2                0.01
album.album_type                          2                0.01
album.name                                2                0.01
album.artists                             2                0.01
track_number                              1                0.01
popularity                                1                0.01
type.x                                    1                0.01
is_local                                  0                0.00
duration_ms.x                             0                0.00
href                                      0                0.00
available_markets                         0                0.00
disc_number                               0                0.00
explicit                                  0                0.00
artists                                   0                0.00

Total Missing Cells: 7707
Rows with Missing Values: 7532
Columns with Missing Values: 39


#### Observation

The original Spotify dataset contains missing values in multiple columns.

The preview_url attribute has a relatively large number of missing values compared with several other attributes.

Some audio features and metadata columns also contain missing values.

These issues will be investigated during Week 3 to determine whether imputation, removal, or preservation is appropriate.


### 8. Duplicate Record Analysis

Duplicate records can affect the accuracy of data analysis.

The `duplicated()` function is used to identify exact duplicate rows.

Spotify song identifiers are also examined separately to identify repeated song entries.

No records are removed during Week 2.

In [41]:

# Exact duplicate records
duplicate_rows = df.duplicated().sum()

print("Exact Duplicate Rows:", duplicate_rows)

# Identify repeated Spotify song IDs
if "id" in df.columns:
    duplicate_ids = df["id"].duplicated().sum()
    print("Repeated Spotify IDs:", duplicate_ids)
else:
    print("Column 'id' not found.")

Exact Duplicate Rows: 0
Repeated Spotify IDs: 2


#### Observation

The dataset contains no exact duplicate rows.

Repeated Spotify identifiers are examined separately because the same song may appear in multiple records.

Any repeated identifiers will be investigated before deciding whether records should be removed.


### 9. Data Type Analysis

Correct data types are important for statistical analysis and visualization.

The dataset contains numerical, categorical, and date-related attributes.

Some columns may contain numerical values stored as text.

This section identifies the current data types and checks for possible inconsistencies without modifying the original dataset.

In [42]:

dtype_report = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Unique Values": df.nunique(dropna=True).values
})

display(dtype_report)

print("\nData Type Distribution:")
print(df.dtypes.value_counts())

                     Column Name Data Type  Unique Values
0                             id       str          19332
1                        artists       str           8788
2              available_markets       str            786
3                    disc_number     int64             10
4                  duration_ms.x       str          14072
5                       explicit       str              5
6                           href       str          19334
7                       is_local       str              5
8                           name       str          16232
9                     popularity       str            104
10                   preview_url       str          11549
11                  track_number       str            375
12                        type.x       str              5
13                         uri.x       str          19332
14              album.album_type       str              6
15                 album.artists       str           5813
16       album.available_markets       str            759
17                    album.href       str          11035
18                      album.id       str          11035
19                  album.images       str          11035
20                    album.name       str          10585
21            album.release_date       str           3350
22  album.release_date_precision       str              6
23            album.total_tracks       str            115
24                    album.type       str              4
25                     album.uri       str          11032
26   album.external_urls.spotify       str          11031
27             external_ids.isrc       str          17455
28         external_urls.spotify       str          19328
29                  danceability   float64            961
30                        energy   float64           1478
31                           key   float64             12
32                      loudness   float64           9757
33                          mode   float64              2
34                   speechiness   float64           1280
35                  acousticness   float64           3042
36              instrumentalness   float64           3777
37                      liveness   float64           1464
38                       valence   float64           1390
39                         tempo   float64          14335
40                        type.y       str              1
41                         uri.y       str          19328
42                    track_href       str          19328
43                  analysis_url       str          19328
44                 duration_ms.y   float64          14089
45                time_signature   float64              5

Data Type Distribution:
str        32
float64    13
int64       1
Name: count, dtype: int64

In [43]:

# Check whether selected fields contain
# values that cannot be converted to numbers

numeric_candidates = [
    "popularity",
    "track_number",
    "duration_ms.x"
]

for col in numeric_candidates:
    if col in df.columns:
        converted = pd.to_numeric(
            df[col],
            errors="coerce"
        )

        invalid_count = (
            df[col].notna() & converted.isna()
        ).sum()

        print(
            f"{col}: {invalid_count} invalid numeric values"
        )

popularity: 1 invalid numeric values
track_number: 1 invalid numeric values
duration_ms.x: 4 invalid numeric values


#### Observation

The dataset contains attributes with different data types.

Some numerical fields are stored as object data types and may require conversion.

The validation process identifies values that cannot be directly converted into numerical form.

Data type correction will be performed during Week 3.


### 10. Automated First Impression Data Quality Report

The First Impression Data Quality Report summarizes the initial condition of the Spotify dataset.

The report includes:

1. Column names
2. Data types
3. Non-null counts
4. Missing values
5. Missing percentages
6. Unique values

The report is generated automatically using Pandas and exported as a CSV file.

This report will be used to plan data cleaning activities in Week 3.

In [44]:

quality_report = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Non-Null Count": df.notnull().sum().values,
    "Missing Count": df.isnull().sum().values,
    "Missing Percentage": (
        df.isnull().mean() * 100
    ).round(2).values,
    "Unique Values": df.nunique(dropna=True).values
})

display(quality_report)

quality_report.to_csv(
    "Week2_Data_Quality_Report.csv",
    index=False
)

print("Data Quality Report generated successfully!")

,Column Name,Data Type,Non-Null Count,Missing Count,Missing Percentage,Unique Values
0,id,str,19333,2,0.01,19332
1,artists,str,19335,0,0.00,8788
2,available_markets,str,19335,0,0.00,786
3,disc_number,int64,19335,0,0.00,10
4,duration_ms.x,str,19335,0,0.00,14072
5,explicit,str,19335,0,0.00,5
6,href,str,19335,0,0.00,19334
7,is_local,str,19335,0,0.00,5
8,name,str,19333,2,0.01,16232
9,popularity,str,19334,1,0.01,104
10,preview_url,str,11811,7524,38.91,11549
11,track_number,str,19334,1,0.01,375
12,type.x,str,19334,1,0.01,5
13,uri.x,str,19333,2,0.01,19332
14,album.album_type,str,19333,2,0.01,6
15,album.artists,str,19333,2,0.01,5813
16,album.available_markets,str,19333,2,0.01,759
17,album.href,str,19333,2,0.01,11035
18,album.id,str,19333,2,0.01,11035
19,album.images,str,19333,2,0.01,11035
20,album.name,str,19333,2,0.01,10585
21,album.release_date,str,19331,4,0.02,3350
22,album.release_date_precision,str,19331,4,0.02,6
23,album.total_tracks,str,19331,4,0.02,115
24,album.type,str,19331,4,0.02,4
25,album.uri,str,19331,4,0.02,11032
26,album.external_urls.spotify,str,19328,7,0.04,11031
27,external_ids.isrc,str,19328,7,0.04,17455
28,external_urls.spotify,str,19328,7,0.04,19328
29,danceability,float64,19328,7,0.04,961
30,energy,float64,19328,7,0.04,1478
31,key,float64,19328,7,0.04,12
32,loudness,float64,19328,7,0.04,9757
33,mode,float64,19328,7,0.04,2
34,speechiness,float64,19328,7,0.04,1280
35,acousticness,float64,19328,7,0.04,3042
36,instrumentalness,float64,19328,7,0.04,3777
37,liveness,float64,19328,7,0.04,1464
38,valence,float64,19328,7,0.04,1390
39,tempo,float64,19328,7,0.04,14335
40,type.y,str,19328,7,0.04,1
41,uri.y,str,19328,7,0.04,19328
42,track_href,str,19328,7,0.04,19328
43,analysis_url,str,19328,7,0.04,19328
44,duration_ms.y,float64,19328,7,0.04,14089
45,time_signature,float64,19328,7,0.04,5

Data Quality Report generated successfully!

In [45]:

summary = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Missing Cells",
        "Rows with Missing Values",
        "Columns with Missing Values",
        "Exact Duplicate Rows",
        "Memory Usage (MB)"
    ],
    "Value": [
        df.shape[0],
        df.shape[1],
        int(df.isnull().sum().sum()),
        int(df.isnull().any(axis=1).sum()),
        int((df.isnull().sum() > 0).sum()),
        int(df.duplicated().sum()),
        round(
            df.memory_usage(deep=True).sum()
            / (1024 ** 2),
            2
        )
    ]
})

display(summary)

summary.to_csv(
    "Week2_Dataset_Summary.csv",
    index=False
)

                        Metric     Value
0                   Total Rows  19335.00
1                Total Columns     46.00
2                Missing Cells   7707.00
3     Rows with Missing Values   7532.00
4  Columns with Missing Values     39.00
5         Exact Duplicate Rows      0.00
6            Memory Usage (MB)     74.65


#### Observation

The automated Data Quality Report summarizes the structure and completeness of all 46 columns.

It identifies missing values, data types, and the number of unique values in each attribute.

The overall dataset summary provides key quality metrics such as duplicate counts and missing records.

These reports provide a foundation for data cleaning and preprocessing in Week 3.


### 11. Conclusion

The Spotify Songs dataset was successfully loaded and examined using Python, Pandas, and NumPy.

The original dataset contains 19,335 rows and 46 columns, including song information, artist details, album metadata, popularity, and audio features.

The initial analysis identified missing values and possible data type inconsistencies.

No exact duplicate rows were identified.

An automated First Impression Data Quality Report was generated to summarize the structure and completeness of the dataset.

The original dataset was preserved without modification.

The findings will guide the data cleaning and preprocessing activities in Week 3.

#### Result

The structure, data types, missing values, duplicate records, and initial quality of the Spotify Songs dataset were successfully examined.

The First Impression Data Quality Report was generated and exported successfully.